
language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: s3
  access_key_id: <insert>
  secret_access_key: <insert>
  bucket: awf-example.com
  local-dir: git_tst
  region: us-west-2
  skip_cleanup: true
